# Direct and inverse geometry of 3d robots
This notebook introduces the kinematic tree of Pinocchio for a serial manipulator, explain how to compute the forward and inverse geometry (from configuration to end-effector placements, and inversely). The ideas are examplified with a simplified case-study taken from parallel robotics.

**Important: to make sure your repository is easily updated from git shall it be needed, create a copy of this notebook before working on it.**

In [1]:
import magic_donotload

NB: as for all the tutorials, a magic command %do_not_load is introduced to hide the solutions to some questions. Change it for %load if you want to see (and execute) the solution.


## Set up
We will need Pinocchio, meshcat and SciPy for the solvers

In [2]:
import time
import math
import numpy as np
from numpy.linalg import norm
import pinocchio as pin
import example_robot_data as robex
from scipy.optimize import fmin_bfgs

## Kinematic tree in Pinocchio
Let's now play with 3D robots. We will load the models from URDF files.

*The robot UR5* is a low-cost manipulator robot with good performances. It is a fixed robot with one 6-DOF arms developed by the Danish company Universal Robot. All its 6 joints are revolute joints. Its configuration is in $\mathbb{R}^6$ and is not subject to any constraint. The model of UR5 is described in a URDF file, with the visuals of the bodies of the robot being described as meshed (i.e. polygon soups) using the Collada format ".dae". Both the URDF and the DAE files are available in the repository in the model directory. 

This robot model, as well as other models used in the notebooks, are installed from the apt paquet example-robot-data.


In [3]:
# %load lab_0/generated/simple_pick_and_place_1
robot = robex.load("ur5")


The kinematic tree is represented by two C++ objects called Model (which contains the model constants: lengths, masses, names, etc) and Data (which contains the working memory used by the model algorithms). Both C\++ objects are contained in a unique Python class, called RobotWrapper.

In [4]:
print(robot.model)

Nb joints = 7 (nq=6,nv=6)
  Joint 0 universe: parent=0
  Joint 1 shoulder_pan_joint: parent=0
  Joint 2 shoulder_lift_joint: parent=1
  Joint 3 elbow_joint: parent=2
  Joint 4 wrist_1_joint: parent=3
  Joint 5 wrist_2_joint: parent=4
  Joint 6 wrist_3_joint: parent=5



Here are some import methods of the RobotWrapper class.


* robot.q0 contains a reference initial configuration of the robot (not a pretty good one for the UR-5).

In [8]:
robot.q0

array([0., 0., 0., 0., 0., 0.])

* robot.index('joint name') returns the index of the joint.

In [5]:
robot.index(' wrist_3_joint')

7

* robot.model.names is a container (~list) that contains all the joint names

In [6]:
for i, n in enumerate(robot.model.names):
    print(i, n)

0 universe
1 shoulder_pan_joint
2 shoulder_lift_joint
3 elbow_joint
4 wrist_1_joint
5 wrist_2_joint
6 wrist_3_joint


* robot.model.frames contains all the import frames attached to the robot. 

In [7]:
for f in robot.model.frames:
    print(f.name, 'attached to joint #', f.parent)

universe attached to joint # 0
world attached to joint # 0
world_joint attached to joint # 0
base_link attached to joint # 0
base_link-base_fixed_joint attached to joint # 0
base attached to joint # 0
shoulder_pan_joint attached to joint # 1
shoulder_link attached to joint # 1
shoulder_lift_joint attached to joint # 2
upper_arm_link attached to joint # 2
elbow_joint attached to joint # 3
forearm_link attached to joint # 3
wrist_1_joint attached to joint # 4
wrist_1_link attached to joint # 4
wrist_2_joint attached to joint # 5
wrist_2_link attached to joint # 5
wrist_3_joint attached to joint # 6
wrist_3_link attached to joint # 6
ee_fixed_joint attached to joint # 6
ee_link attached to joint # 6
wrist_3_link-tool0_fixed_joint attached to joint # 6
tool0 attached to joint # 6


/tmp/ipykernel_9105/2471843488.py:2: UserWarning: Deprecated member. Use Frame.parentJoint instead.
  print(f.name, 'attached to joint #', f.parent)


* robot.placement(q, idx) and robot.framePlacement(idx) returns the placement (i.e. translation+rotation of the joint / frame) in argument for a given configuration.

In [8]:
robot.placement(robot.q0, 6)  # Placement of the end effector.

SE3(array([[-1.0000000e+00,  0.0000000e+00,  9.7932773e-12,  8.1725000e-01],[ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00,  1.0915000e-01],[-9.7932773e-12,  0.0000000e+00, -1.0000000e+00, -5.4910000e-03],[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]]))

The dimension of the configuration space (i.e. the number of joints) is given in:

In [9]:
NQ = robot.model.nq
NV = robot.model.nv  # for this simple robot, NV == NQ

## Display simple geometries
The robot is displayed in the viewer. We are going to use Meshcat to visualize the 3d robot and scene. First open the viewer and load the robot geometries.

In [10]:
from utils.meshcat_viewer_wrapper import MeshcatVisualizer, colors  # noqa: E402

viz = MeshcatVisualizer(robot)

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/


In [11]:
viz.viewer.jupyter_cell()

As a reminder, a configuration *q* can be displayed in the viewer:

In [25]:
q = np.array([0, 1.5, 0.5, 0, 0, 0])*np.pi

viz.display(q)

Other geometries (cubes, spheres, etc) can be displayed as well.

In [78]:
# %load lab_0/generated/simple_pick_and_place_2
# Add a red box in the viewer
ballID = "world/ball"
viz.addSphere(ballID, 0.1, colors.red)

# Place the ball at the position ( 0.5, 0.1, 0.2 )
# The viewer expect position and rotation, apppend the identity quaternion
q_ball = [0.5, 0.1, 0.2, 1, 0, 0, 0]
viz.applyConfiguration(ballID, q_ball)


# Forward (direct) geometry

First, let's do some forward geometry, i.e. use Pinocchio to compute where is the end effector knowning the robot configuration. To achieve this we are going to emulate a pick and place scenario (with no physics involved). The red ball we created will be attached to the end effector and thus must move along with it.

# Simple pick ...

Say we have a target at position [.5,.1,.2] and we would like the robot to grasp it.
First decide (by any way you want, e.g. trial and error) the configuration of the robot so that the end effector touches the ball. For that, modify the template code below.


In [57]:
q0 = np.zeros(NQ)  # set the correct values here
q0[0] = -0.1
q0[1] = -0.4
q0[2] = -1.45
q0[3] = 0.
q0[4] = 0.
q0[5] = 0.

q0 = q0.copy() * np.pi

viz.display(q0)

# Take care to explicitely mention copy when you want a copy of array.
q = q0.copy() * np.pi

Here is a the solution, should you need it.

In [88]:
# %load lab_0/generated/simple_pick_and_place_3
q0 = np.zeros(NQ)  # set the correct values here
q0[0] = -0.375
q0[1] = -1.2
q0[2] = 1.71
q0[3] = -q0[1] - q0[2]
q0[4] = q0[0]
q0[5] = 0.0

viz.display(q0)
q_init = q0.copy()


# ... and simple place

At the reference position you built, the end effector placement can be obtained by calling 

In [ ]:
robot.placement(q, 6).translation

SE3(array([[-0.97195203, -0.11008565,  0.20782299,  0.48578545],[-0.1101395 ,  0.99385135,  0.01134842, -0.23836806],[-0.20779446, -0.0118594 , -0.97810062,  0.16581901],[ 0. ,  0. ,  0. ,  1. ]]))

Only the translation part of the placement has been selected. The rotation is free.

Now, choose any trajectory you want in the configuration space (it can be sinus-cosinus waves, polynomials, splines, straight lines). Make a for loop to display the robot at sampling positions along this trajectory. The function sleep can be used to slow down the loop.

In [66]:
q_ball = [0.5, 0.1, 0.2, 1, 0, 0, 0]
for i in range(50):
    q0 = np.array([np.sin(i/10), np.sin(i/10), np.sin(i/10), np.sin(i/10), np.sin(i/10), np.sin(i/10)]) * np.pi
    q = q0.copy()
    endeff = robot.placement(q, 6).translation
    q_ball[0:3] = endeff
    viz.applyConfiguration(ballID, q_ball)
    viz.display(q0)
    time.sleep(.1)  # in second

At each instant of your loop, recompute the position of the ball and display it so that it always "sticks" to the robot end effector, by modifying the template code below:

In [113]:
q_ball = [0.5, 0.1, 0.2, 1, 0, 0, 0]
viz.applyConfiguration(ballID, q_ball)

# TODO ####################################################
# Replace here with your initial configuration

q0 = np.zeros(NQ)  # set the correct values here
q0[0] = -0.375
q0[1] = -1.2
q0[2] = 1.71
q0[3] = -q0[1] - q0[2]
q0[4] = q0[0]
q0[5] = 0.0
viz.display(q0)
# q0 = np.random.rand(NQ) * 6 - 3
q = q0.copy()

# # TODO ####################################################

# Compute initial translation between effector and box.
# Translation of end-eff wrt world at initial configuration
o_eff = robot.placement(q, 6).translation
# Translation of ball wrt world
o_ball = q_ball[:3]
eff_ball = o_ball - o_eff

print(eff_ball)



for i in range(10):
    # Replace here by your choice of computing q(t)
    q += np.random.rand(6) * 2e-1 - 1e-1

    # TODO ####################################################
    # Replace here by your computation of the new box position
    o_ball = robot.placement(q, 6).translation + eff_ball
    # /TODO ###################################################

    # Display the new robot and box configurations.
    # The viewer expect a placement (position-rotation).
    viz.applyConfiguration(ballID, o_ball.tolist() + [1, 0, 0, 0])
    viz.display(q)
    time.sleep(0.1)

print(o_ball - o_eff)

[-0.00182315  0.18022936  0.00086191]
[-0.00182315  0.18022936  0.00086191]


The solution is below, should you need it.

In [116]:
# %load lab_0/generated/simple_pick_and_place_4
q = q_init.copy()
# Random velocity of the robot driving the movement
vq = np.array([2.0, 0, 0, 4.0, 0, 0])

idx = robot.index("wrist_3_joint")
o_eff = robot.placement(
    q, idx
).translation  # Position of end-eff wrt world at current configuration
o_ball = q_ball[:3]  # Position of ball wrt world
eff_ball = o_ball - o_eff  # Position of ball wrt eff

for i in range(100):
    # Chose new configuration of the robot
    q = q + vq / 40
    q[2] = 1.71 + math.sin(i * 0.05) / 2

    # Gets the new position of the ball
    o_ball = robot.placement(q, 6) * eff_ball
    print(robot.placement(q, 6))
    print(eff_ball)
    # Why are we multiplying by the vector rather than adding it?

    # Display new configuration for robot and ball
    viz.applyConfiguration(ballID, o_ball.tolist() + [1, 0, 0, 0])
    viz.display(q)
    time.sleep(1e-2)



  R =
 -0.994345 -0.0482451 -0.0946072
-0.0514635   0.998166  0.0318777
 0.0928958  0.0365662  -0.995004
  p =   0.496251 -0.0520312   0.199611

[-0.00182315  0.18022936  0.00086191]
  R =
 -0.972433 -0.0909489  -0.214713
 -0.106202   0.992497  0.0605811
  0.207593   0.081714  -0.974796
  p =   0.482295 -0.0226675   0.193029

[-0.00182315  0.18022936  0.00086191]
  R =
-0.933805 -0.127802 -0.334178
-0.162019  0.983819 0.0764852
 0.318996  0.125565 -0.939401
  p =   0.466818 0.00512916   0.188031

[-0.00182315  0.18022936  0.00086191]
  R =
-0.878744 -0.158786 -0.450107
-0.216584  0.973015 0.0795828
 0.425324  0.167419 -0.889421
  p =   0.45014 0.0312544  0.184584

[-0.00182315  0.18022936  0.00086191]
  R =
-0.808001 -0.184065 -0.559692
-0.267623  0.960954 0.0703282
 0.524893  0.206612 -0.825711
  p =  0.432581 0.0556524  0.182629

[-0.00182315  0.18022936  0.00086191]
  R =
-0.722769 -0.203976 -0.660302
-0.312996  0.948458 0.0496157
 0.616148  0.242532  -0.74936
  p =  0.414453 0.0783

### Pick and place in 6D

Say now that the object is a rectangle and not a sphere. Pick the object at a reference position with the rotation that is imposed, so that the end effector is aligned with one of the faces of the rectangle.


In [31]:
# %load lab_0/generated/simple_pick_and_place_5
# Add a purple box to the viewer
boxID = "world/box"
# viz.delete(ballID)
viz.addBox(boxID, [0.1, 0.2, 0.1], colors.magenta)

# Place the box at the position (0.5, 0.1, 0.2)
q_box = [0.5, 0.1, 0.2, 1, 0, 0, 0]
viz.applyConfiguration(boxID, q_box)
viz.applyConfiguration(ballID, [2, 2, 2, 1, 0, 0, 0])


A configuration with the arm nicely attached to the box is:

In [32]:
# %load lab_0/generated/simple_pick_and_place_6
q0 = np.zeros(NQ)
q0[0] = -0.375
q0[1] = -1.2
q0[2] = 1.71
q0[3] = -q0[1] - q0[2]
q0[4] = q0[0]

viz.display(q0)
q = q0.copy()


Redo the same question as before, but now also choosing the orientation of the box. For that, at each robot configuration in the for-loop, we will compute the entire box placement with respect the world (let's denote it by oMbox) and display both the box and the robot configuration in the view.

In [34]:
# %load lab_0/generated/simple_pick_and_place_7
# Random velocity of the robot driving the movement
vq = np.array([2., 0, 0, 4., 0, 0])
q = q0.copy()
idx = robot.index('wrist_3_joint')
oMeff = robot.placement(q, idx)  # Placement of end-eff wrt world at current configuration
oMbox = pin.XYZQUATToSE3(q_box)  # Placement of box     wrt world
effMbox = oMeff.inverse() * oMbox  # Placement of box     wrt eff

for i in range(100):
    # Chose new configuration of the robot
    q += vq / 40
    q[2] = 1.71 + math.sin(i * 0.05) / 2

    # Gets the new position of the box
    oMbox = robot.placement(q, idx) * effMbox

    # Display new configuration for robot and box
    viz.applyConfiguration(boxID, oMbox)
    viz.display(q)
    time.sleep(1e-2)


## Inverse geometry

As you can see, forward geometry is easy to implement in pinocchio. Let's not see how to deal with inverse geometry.

### Inverse geometry in 3D

Let's now first control the position (i.e. translation only) of the end effector of a manipulator robot to a given position. For this first part, we will use the fixed serial-chain robot model.

Recall first that the position (3D) of the joint with index "i=6" at position "q" can be accessed with:

In [35]:
robot.placement(q, 6).translation

array([ 0.06033124, -0.56198697,  0.57011662])

Using the scipy solver [used in the previous notebook](2_inv_geom.ipynb#section_optim), compute a configuration q where the end effector reaches p. For that, implement a cost function that takes a configuration as argument and returns the squared distance between the end effetor and the target.

In [36]:
%do_not_load lab_0/generated/invgeom3d_1

### Inverse geometry in 6D
Now, let's update the previous cost function for measuring the "distance" between the current placement root.placement(q,6) and a reference placement oMtarget. 
For that, you can use the SE(3) log function to score the distance between two placements. The log returns a 6D velocity, represented by a class Motion, that must be transformed to a vector of R^6 from which you can take the norm.


In [39]:
pin.log(pin.SE3.Identity()).vector

array([0., 0., 0., 0., 0., 0.])

As a target we can define

In [40]:
oMtarget = pin.SE3(pin.utils.rotate("x", 3.14 / 4), np.array([-0.5, 0.1, 0.2]))  # x,y,z

In [ ]:
# %load lab_0/generated/invgeom6d_1
# Add a vizualisation for the tip of the arm.
tipID = "world/blue"
viz.addBox(tipID, [0.08] * 3, [0.2, 0.2, 1.0, 0.5])

#
# OPTIM 6D #########################################################
#
def cost(q):
    """Compute score from a configuration"""
    M = robot.placement(q, 6)
    return norm(pin.log(M.inverse() * oMtarget).vector)


def callback(q):
    viz.applyConfiguration(boxID, oMtarget)
    viz.applyConfiguration(tipID, robot.placement(q, 6))
    viz.display(q)
    time.sleep(1e-1)

qopt = fmin_bfgs(cost, robot.q0, callback=callback)

print("The robot finally reached effector placement at\n", robot.placement(qopt, 6))


### Optimizing in the quaternion space

Let's now work with a floating robot: the quadruped solo. This robot has 12 joints, but it's configuration (Q-space) is of dimension 19 (robot.model.nq). Its tangent space (where the velocities are expressed) is of dimension 18 (robot.model.nv). This is because we need 7D vector to encode the robot placement in space (a 3D position and a 4D quaternion).


In [42]:
robot = robex.load('solo12')
viz = MeshcatVisualizer(robot)
viz.viewer.jupyter_cell()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7002/static/


In [43]:
viz.display(robot.q0)


Run the following code. Can you explain what just happened? Then correct it to have a proper optimization of ANYmal configuration.

In [44]:
# %load lab_0/generated/floating_1
robot.feetIndexes = [
    robot.model.getFrameId(frameName)
    for frameName in ["HR_FOOT", "HL_FOOT", "FR_FOOT", "FL_FOOT"]
]

# --- Add box to represent target
colors = ["red", "blue", "green", "magenta"]
for color in colors:
    viz.addSphere("world/%s" % color, 0.05, color)
    viz.addSphere("world/%s_des" % color, 0.05, color)

#
# OPTIM 6D #########################################################
#

targets = [
    np.array([-0.7, -0.2, 1.2]),
    np.array([-0.3, 0.5, 0.8]),
    np.array([0.3, 0.1, -0.1]),
    np.array([0.9, 0.9, 0.5]),
]
for i in range(4):
    targets[i][2] += 1


def cost(q):
    """Compute score from a configuration"""
    cost = 0.0
    for i in range(4):
        p_i = robot.framePlacement(q, robot.feetIndexes[i]).translation
        cost += norm(p_i - targets[i]) ** 2
    return cost


def callback(q):
    for i in range(4):
        p_i = robot.framePlacement(q, robot.feetIndexes[i])
        viz.applyConfiguration("world/%s" % colors[i], p_i)
        viz.applyConfiguration(
            "world/%s_des" % colors[i], list(targets[i]) + [1, 0, 0, 0]
        )
    
    viz.display(q)
    time.sleep(1e-2)


Mtarget = pin.SE3(pin.utils.rotate("x", 3.14 / 4), np.array([0.5, 0.1, 0.2]))  # x,y,z
qopt = fmin_bfgs(cost, robot.q0, callback=callback)


Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 46
         Function evaluations: 1060
         Gradient evaluations: 53


## Optional Configuration of parallel robots

The following exercise is optional and won't be corrected, but you are free to discuss it on piazza.

A parallel robot is composed of several kinematic chains (called the robot legs) that are all attached to the same end effector. This imposes strict constraints in the configuration space of the robot: a configuration is valide iff all the legs meets the same end-effector placement. We consider here only the geometry aspect of parallel robots (additionnally, some joints are not actuated, which causes additional problems).

The kinematic structure of a parallel robot indeed induces loops in the joint connection graph. In Pinocchio, we can only represent (one of) the underlying kinematic tree. The loop constraints have to be handled separately. An example that loads 4 manipulator arms is given below.

In [46]:
from utils.load_ur5_parallel import load_ur5_parallel  # noqa: E402

robot = load_ur5_parallel()

ModuleNotFoundError: No module named 'utils.load_ur5_parallel'

In [104]:
viz = MeshcatVisualizer(robot)
viz.viewer.jupyter_cell()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7009/static/


In [109]:
viz.display(robot.q0)

In [110]:
[w, h, d] = [0.5, 0.5, 0.005]
color = [red, green, blue, transparency] = [1, 1, 0.78, .8]
viz.addBox('world/robot0/toolplate', [w, h, d], color)
Mtool = pin.SE3(pin.utils.rotate('z', 1.268), np.array([0, 0, .75]))
viz.applyConfiguration('world/robot0/toolplate', Mtool)

The 4 legs of the robot are loaded in a single robot model. The 4 effector placements are computed by:

In [111]:
effIdxs = [robot.model.getFrameId('tool0_#%d' % i) for i in range(4)]
robot.framePlacement(robot.q0, effIdxs[0])

  R =
   -0.707107    -0.707107 -3.46245e-12
    0.707107    -0.707107 -3.46236e-12
-6.12323e-17 -4.89664e-12            1
  p = 0.306122 0.160483 0.749342

The loop constraints are that the relative placement of every leg end-effector must stay the same as it was in the initial configuration (at the configuration *robot.q0*) and the plate placement *Mtool*. To be valid, a configuration *q* must satisfy these 4 relative placement constraints.

Consider now that the orientation of the tool plate is given by the following quaternion, with the translation that you like (see [the notebook about rotations if you need more details](appendix_quaternions.ipynb)): 



In [108]:
quat = pin.Quaternion(0.7, 0.2, 0.2, 0.6).normalized()
print(quat.matrix())

[[ 0.13978495 -0.8172043   0.55913978]
 [ 0.98924731  0.13978495 -0.04301075]
 [-0.04301075  0.55913978  0.82795699]]


**Find using the above optimization routines the configuration of each robot leg so that the loop constraints are all met** for the new orientation of the plate.